"""empty message

Revision ID: f71a6671704c
Revises: 558902804a6b
Create Date: 2020-10-14 14:20:54.046953

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'f71a6671704c'
down_revision = '558902804a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stats',
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('probe_uuid', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.Column('kernel', sa.String(length=32), nullable=True),
    sa.Column('distro', sa.String(length=32), nullable=True),
    sa.Column('machine_name', sa.String(length=64), nullable=True),
    sa.Column('machine', sa.String(length=64), nullable=True),
    sa.Column('ram_available', sa.Integer(), nullable=True),
    sa.Column('ram_free', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stats')
    # ### end Alembic commands ###
